export enum ReportType {
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  TECHNICAL = 'TECHNICAL',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

export enum ReportPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AnnouncementReportCategory {
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  OUTDATED_INFO = 'OUTDATED_INFO',
  WRONG_ADDRESS = 'WRONG_ADDRESS',
  WRONG_DATE_TIME = 'WRONG_DATE_TIME',
  WRONG_CAPACITY = 'WRONG_CAPACITY',
  INAPPROPRIATE_TAGS = 'INAPPROPRIATE_TAGS',
  OTHER = 'OTHER',
}

export enum TechnicalReportCategory {
  CONNECTION_ISSUE = 'CONNECTION_ISSUE',
  IMAGE_NOT_LOADING = 'IMAGE_NOT_LOADING',
  RESPONSIVE_ISSUE = 'RESPONSIVE_ISSUE',
  SEARCH_PROBLEM = 'SEARCH_PROBLEM',
  FORM_NOT_WORKING = 'FORM_NOT_WORKING',
  SLOW_PERFORMANCE = 'SLOW_PERFORMANCE',
  OTHER = 'OTHER',
}
