global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files: ["alert_rules.yml"]
scrape_configs:
  - job_name: 'prometheus'
    static_configs: [{'targets': ['localhost:9090']}]
  - job_name: 'benevoclic-api'
    static_configs: [{'targets': ['benevoclic-api:3000']}]
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.+)'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        regex: '(.+)'
        replacement: 'benevoclic-api'
  - job_name: 'node-exporter'
    static_configs: [{'targets': ['node-exporter:9100']}]
    scrape_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]