import { ObjectId } from 'mongodb';

export const sampleAnnouncements = [
  {
    _id: new ObjectId('687aa7e85cb7bfff2aa313d1'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Rejoignez-nous pour nettoyer le parc.',
    datePublication: '2025-07-01',
    dateEvent: '2025-07-21',
    hoursEvent: '09:00',
    nameEvent: 'Nettoyage du parc',
    tags: ['environnement', 'solidarité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '10 Rue de la République',
      city: 'Paris',
      postalCode: '75000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [2.3522, 48.8566],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-01T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7e95cb7bfff2aa313d2'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Aidez-nous à distribuer des repas.',
    datePublication: '2025-07-02',
    dateEvent: '2025-07-22',
    hoursEvent: '12:30',
    nameEvent: 'Distribution de repas',
    tags: ['solidarité', 'santé'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '5 Avenue Jean Jaurès',
      city: 'Lyon',
      postalCode: '69000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [4.8357, 45.764],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-02T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7ea5cb7bfff2aa313d3'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Participez à notre atelier de jardinage.',
    datePublication: '2025-07-03',
    dateEvent: '2025-07-23',
    hoursEvent: '14:00',
    nameEvent: 'Atelier de jardinage',
    tags: ['éducation', 'environnement'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: "15 Boulevard de l'Europe",
      city: 'Marseille',
      postalCode: '13000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [5.3698, 43.2965],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-03T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7eb5cb7bfff2aa313d4'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Donnez vos vêtements inutilisés.',
    datePublication: '2025-07-04',
    dateEvent: '2025-07-24',
    hoursEvent: '10:30',
    nameEvent: 'Collecte de vêtements',
    tags: ['solidarité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '20 Rue Gustave Eiffel',
      city: 'Toulouse',
      postalCode: '31000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [1.444, 43.6045],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-04T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7ec5cb7bfff2aa313d5'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Sensibilisation au tri des déchets.',
    datePublication: '2025-07-05',
    dateEvent: '2025-07-25',
    hoursEvent: '11:15',
    nameEvent: 'Sensibilisation au tri',
    tags: ['environnement'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '7 Rue de la Liberté',
      city: 'Nice',
      postalCode: '06000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [7.262, 43.7102],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-05T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7ed5cb7bfff2aa313d6'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Visite guidée du musée local.',
    datePublication: '2025-07-06',
    dateEvent: '2025-07-26',
    hoursEvent: '15:00',
    nameEvent: 'Visite musée',
    tags: ['culture'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '3 Place du Palais',
      city: 'Nantes',
      postalCode: '44000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [-1.5536, 47.2184],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-06T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7ee5cb7bfff2aa313d7'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Découverte de sports collectifs.',
    datePublication: '2025-07-07',
    dateEvent: '2025-07-27',
    hoursEvent: '16:30',
    nameEvent: 'Initiation sport',
    tags: ['sport'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '12 Avenue du Stade',
      city: 'Strasbourg',
      postalCode: '67000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [7.7521, 48.5734],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-07T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7ef5cb7bfff2aa313d8'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier de peinture en plein air.',
    datePublication: '2025-07-08',
    dateEvent: '2025-07-28',
    hoursEvent: '13:00',
    nameEvent: 'Atelier peinture',
    tags: ['culture', 'éducation'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '8 Rue des Arts',
      city: 'Montpellier',
      postalCode: '34000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.8767, 43.6108],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-08T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f05cb7bfff2aa313d9'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Participez à la collecte de livres.',
    datePublication: '2025-07-09',
    dateEvent: '2025-07-29',
    hoursEvent: '10:00',
    nameEvent: 'Collecte de livres',
    tags: ['éducation'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '2 Rue de la Librairie',
      city: 'Bordeaux',
      postalCode: '33000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [-0.5792, 44.8378],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-09T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f15cb7bfff2aa313da'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Aide bénévole aux devoirs.',
    datePublication: '2025-07-10',
    dateEvent: '2025-07-30',
    hoursEvent: '14:45',
    nameEvent: 'Aide aux devoirs',
    tags: ['éducation', 'jeunesse'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '18 Rue Victor Hugo',
      city: 'Rennes',
      postalCode: '35000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [-1.6778, 48.1173],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-10T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f25cb7bfff2aa313db'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Tournoi caritatif de football.',
    datePublication: '2025-07-11',
    dateEvent: '2025-07-31',
    hoursEvent: '17:00',
    nameEvent: 'Tournoi sportif',
    tags: ['sport', 'solidarité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '25 Boulevard du Sport',
      city: 'Grenoble',
      postalCode: '38000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [5.7245, 45.1885],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-11T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f35cb7bfff2aa313dc'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Course solidaire pour la santé.',
    datePublication: '2025-07-12',
    dateEvent: '2025-08-01',
    hoursEvent: '09:30',
    nameEvent: 'Course solidaire',
    tags: ['santé', 'solidarité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '1 Allée de la Santé',
      city: 'Dijon',
      postalCode: '21000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [5.0415, 47.322],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-12T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f45cb7bfff2aa313dd'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Projection en plein air gratuite.',
    datePublication: '2025-07-13',
    dateEvent: '2025-08-02',
    hoursEvent: '21:00',
    nameEvent: 'Cinéma plein air',
    tags: ['culture', 'jeunesse'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: 'Place du Cinéma',
      city: 'Tours',
      postalCode: '37000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [0.6848, 47.3941],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-13T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f55cb7bfff2aa313de'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier de conversation en anglais.',
    datePublication: '2025-07-14',
    dateEvent: '2025-08-03',
    hoursEvent: '10:15',
    nameEvent: 'Cours de langue',
    tags: ['éducation'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: "4 Rue de l'Europe",
      city: 'Clermont-Ferrand',
      postalCode: '63000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.087, 45.7772],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-14T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f65cb7bfff2aa313df'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Chorale ouverte à tous.',
    datePublication: '2025-07-15',
    dateEvent: '2025-08-04',
    hoursEvent: '18:00',
    nameEvent: 'Chant choral',
    tags: ['culture'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '6 Rue de la Musique',
      city: 'Angers',
      postalCode: '49000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [-0.5632, 47.4784],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-15T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f75cb7bfff2aa313e0'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier de réparation de vélos.',
    datePublication: '2025-07-16',
    dateEvent: '2025-08-05',
    hoursEvent: '11:00',
    nameEvent: 'Réparation vélos',
    tags: ['environnement'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '9 Rue du Vélo',
      city: 'Le Havre',
      postalCode: '76600',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [0.1079, 49.4944],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-16T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f85cb7bfff2aa313e1'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier bricolage solidaire.',
    datePublication: '2025-07-17',
    dateEvent: '2025-08-06',
    hoursEvent: '14:00',
    nameEvent: 'Bricolage solidaire',
    tags: ['solidarité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '14 Rue du Bricolage',
      city: 'Reims',
      postalCode: '51100',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [4.0317, 49.2583],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-17T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7f95cb7bfff2aa313e2'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Nettoyage des berges de la rivière.',
    datePublication: '2025-07-18',
    dateEvent: '2025-08-07',
    hoursEvent: '09:00',
    nameEvent: 'Ramassage déchets rivière',
    tags: ['environnement'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: 'Quai de la Rivière',
      city: 'Saint-Étienne',
      postalCode: '42000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [4.3872, 45.4397],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'COMPLETED',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-18T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7fa5cb7bfff2aa313e3'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Jardinage au jardin partagé.',
    datePublication: '2025-07-19',
    dateEvent: '2025-08-08',
    hoursEvent: '15:30',
    nameEvent: 'Jardinage communautaire',
    tags: ['environnement', 'jeunesse'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '20 Rue du Jardin',
      city: 'Toulon',
      postalCode: '83000',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [5.928, 43.1242],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'COMPLETED',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-19T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687aa7fb5cb7bfff2aa313e4'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: "Initiation à l'informatique.",
    datePublication: '2025-07-20',
    dateEvent: '2025-08-09',
    hoursEvent: '16:00',
    nameEvent: 'Atelier informatique',
    tags: ['éducation', 'jeunesse'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '30 Rue du Numérique',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.100788, 50.633568],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-20T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0015cb7bfff2aa313f1'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: "Atelier d'initiation au jardinage urbain.",
    datePublication: '2025-07-21',
    dateEvent: '2025-07-28',
    hoursEvent: '10:00',
    nameEvent: 'Jardinage urbain',
    tags: ['environnement', 'jardinage'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '22 Rue de Paris',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.060114, 50.62925],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-21T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0025cb7bfff2aa313f2'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Collecte de déchets autour du Vieux-Lille.',
    datePublication: '2025-07-22',
    dateEvent: '2025-07-29',
    hoursEvent: '09:30',
    nameEvent: 'Nettoyage Vieux-Lille',
    tags: ['environnement', 'solidarité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: 'Place Rihour',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.057256, 50.637739],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-22T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0035cb7bfff2aa313f3'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Distribution de repas solidaires près de la gare.',
    datePublication: '2025-07-23',
    dateEvent: '2025-07-30',
    hoursEvent: '12:00',
    nameEvent: 'Repas solidaire',
    tags: ['solidarité', 'food'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: 'Place des Buisses',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.061912, 50.640094],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'COMPLETED',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-23T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0045cb7bfff2aa313f4'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier de réparation de vélos communautaire.',
    datePublication: '2025-07-24',
    dateEvent: '2025-08-01',
    hoursEvent: '14:30',
    nameEvent: 'Réparation vélos',
    tags: ['environnement', 'mobilité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '15 Rue Léon Gambetta',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.052965, 50.63565],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-24T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0055cb7bfff2aa313f5'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier couture pour vêtements recyclés.',
    datePublication: '2025-07-25',
    dateEvent: '2025-08-02',
    hoursEvent: '11:00',
    nameEvent: 'Couture solidaire',
    tags: ['éducation', 'recyclage'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '8 Rue Saint-Jacques',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.056182, 50.63297],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-25T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0065cb7bfff2aa313f6'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Projection de film en plein air.',
    datePublication: '2025-07-26',
    dateEvent: '2025-08-03',
    hoursEvent: '21:00',
    nameEvent: 'Cinéma en plein air',
    tags: ['culture', 'jeunesse'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: 'Esplanade du Théâtre',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.055219, 50.631556],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-26T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0075cb7bfff2aa313f7'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier de poterie solidaire.',
    datePublication: '2025-07-27',
    dateEvent: '2025-08-04',
    hoursEvent: '15:00',
    nameEvent: 'Poterie solidaire',
    tags: ['éducation', 'artisanat'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: '12 Rue de Paris',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.060114, 50.62925],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-27T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0085cb7bfff2aa313f8'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Randonnée urbaine solidaire.',
    datePublication: '2025-07-28',
    dateEvent: '2025-08-05',
    hoursEvent: '09:00',
    nameEvent: 'Randonnée solidaire',
    tags: ['sport', 'solidarité'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: 'Parc de la Citadelle',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.057, 50.637],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-28T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab0095cb7bfff2aa313f9'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: 'Atelier de recyclage créatif pour enfants.',
    datePublication: '2025-07-29',
    dateEvent: '2025-08-06',
    hoursEvent: '14:00',
    nameEvent: 'Créa-recyclage',
    tags: ['éducation', 'environnement'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: "Musée d'Histoire Naturelle",
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.066, 50.63],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'ACTIVE',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-29T08:00:00.000Z',
  },
  {
    _id: new ObjectId('687ab00a5cb7bfff2aa313fa'),
    associationId: 'JUAlXG81OoTF4p8kNU0NvwMWzyz2',
    description: "Distribution de kits d'hygiène aux sans-abri.",
    datePublication: '2025-07-30',
    dateEvent: '2025-08-07',
    hoursEvent: '11:30',
    nameEvent: "Kits d'hygiène solidaires",
    tags: ['solidarité', 'santé'],
    associationName: 'benevoclic',
    associationLogo: '',
    announcementImage: '',
    addressAnnouncement: {
      address: 'Gare de Lille Flandres',
      city: 'Lille',
      postalCode: '59800',
      country: 'France',
    },
    locationAnnouncement: {
      type: 'Point',
      coordinates: [3.077, 50.636],
    },
    participants: [],
    volunteers: [],
    volunteersWaiting: [],
    nbParticipants: 0,
    maxParticipants: 2,
    status: 'COMPLETED',
    nbVolunteers: 0,
    maxVolunteers: 2,
    updatedAt: '2025-07-30T08:00:00.000Z',
  },
];
